### ISSUE TITLE
type SimplePlot has no field id

### ISSUE THREAD

**Issue by gnadt** [djsegal/SimplePlots.jl#2]
] add https://github.com/djsegal/SimplePlots.jl
using SimplePlots
scatter(rand(10), label="Scatter", color=4, xlabel="x", markersize=6)

type SimplePlot has no field id
getproperty(::SimplePlots.SimplePlot, ::Symbol) at Base.jl:33
displayinplotpane(::SimplePlots.SimplePlot) at showdisplay.jl:33
displayandrender(::SimplePlots.SimplePlot) at showdisplay.jl:131
(::Atom.var"#189#193"{String})() at eval.jl:126
#invokelatest#1 at essentials.jl:712 [inlined]
invokelatest at essentials.jl:711 [inlined]
macro expansion at dynamic.jl:24 [inlined]
eval(::String, ::Int64, ::String, ::String, ::Bool) at eval.jl:105
macro expansion at eval.jl:39 [inlined]
(::Atom.var"#172#173")() at task.jl:358

**Comment by djsegal** [comment]
Should be working now! Hope you're doing well

Keep me posted if you find any more bugs

**Comment by gnadt** [comment]
Unfortunately still seeing the issue! (after updating the package of course)

Albert

**Comment by djsegal** [comment]
My bad. Didn't realize you were using the REPL plots

Should be fixed now? Although the markersize option doesn't do anything in [UnicodePlots.jl](https://github.com/Evizero/UnicodePlots.jl)

If it isn't can you upload the most recent error? Is it still: `type SimplePlot has no field id`?

**Comment by gnadt** [comment]
No worries. Looks like I'm still getting the "no field id" error.

julia> scatter(rand(10), label="Scatter", color=4, xlabel="x", markersize=6)
Error showing value of type SimplePlots.SimplePlot:
ERROR: type SimplePlot has no field id
Stacktrace:
 [1] getproperty(::SimplePlots.SimplePlot, ::Symbol) at ./Base.jl:33
 [2] displayinplotpane(::SimplePlots.SimplePlot) at /Users/gnadt/.juliapro/JuliaPro_v1.4.0-1/packages/Atom/wlPiw/src/display/showdisplay.jl:33
 [3] display(::Atom.JunoDisplay, ::SimplePlots.SimplePlot) at /Users/gnadt/.juliapro/JuliaPro_v1.4.0-1/packages/Atom/wlPiw/src/display/showdisplay.jl:118
...and on
